---
- name: Configure database server
  hosts: db
  vars:
    - mysql_root_password: super-secure-password
    - mysql_databases:
      - name: my_app_db
        encoding: utf8
        collation: utf8_general_ci
    - mysql_users:
      - name: app_user
        host: "%"
        password: similarly-secure-password
        priv: "my_app_db.*:ALL"
  roles:
    - { role: geerlingguy.mysql,  become: true }
